export const queryKeys = Object.freeze({
  employees: (params = {}) => ["employees", params],
  departments: (params = {}) => ["departments", params],
  categories: (params = {}) => ["categories", params],
  assets: (params = {}) => ["assets", params],
  asset: (id) => ["asset", id],
  assetHistory: (id) => ["asset-history", id],
  allocations: (params = {}) => ["allocations", params],
  transfers: (params = {}) => ["transfers", params],
  bookings: (params = {}) => ["bookings", params],
  maintenance: (params = {}) => ["maintenance", params],
  maintenanceDetail: (id) => ["maintenance-detail", id],
  audits: (params = {}) => ["audits", params],
  audit: (id) => ["audit", id],
  discrepancies: (id) => ["audit-discrepancies", id],
  kpis: () => ["kpis"],
  dashboardReturns: (type) => ["dashboard-returns", type],
  notifications: (params = {}) => ["notifications", params],
  unreadCount: () => ["unread-count"],
  activity: (params = {}) => ["activity", params],
  reports: (name, params = {}) => ["reports", name, params],
});
